#!/bin/bash

set -Cue

function get_wsl_host_addr() {
  if ! grep 'generated by WSL' /etc/resolv.conf > /dev/null; then
    return 0
  fi
  WSL_HOST_ADDR=$(grep nameserver /etc/resolv.conf | awk '{print $2; exit;}')
}

if [ -z "${WSL_HOST_ADDR+x}" ]; then
    get_wsl_host_addr
fi

if [ -z "${WSL_HOST_ADDR+x}" ]; then
  # On pure Linux or macOS
  probe-rs "$@"
else
  # On WSL2
  socat "TCP-LISTEN:$3,fork,reuseaddr" "TCP:${WSL_HOST_ADDR}:$3" &
  probe-rs.exe "$@" --ip 0.0.0.0 &
  wait < <(jobs -p)
fi
