#!/bin/bash

set -Cue

function get_wsl_host_addr() {
  if ! grep 'generated by WSL' /etc/resolv.conf > /dev/null; then
    return 0
  fi
  WSL_HOST_ADDR=$(grep nameserver /etc/resolv.conf | awk '{print $2; exit;}')
}

if [ -z "${WSL_HOST_ADDR+x}" ]; then
    get_wsl_host_addr
fi

# ポート名の環境変数が定義されていない時には空文字に潰す
# jsonnet 側で空文字の場合には無視するようにしている
jrsonnet \
  -V KBLE_SERIALPORT_ADDR="${WSL_HOST_ADDR:-127.0.0.1}" \
  -V PORT_CH_RS422_MOBC_REPRO="${PORT_CH_RS422_MOBC_REPRO:-}" \
  -V PORT_CH_RS422_MOBC_EXT="${PORT_CH_RS422_MOBC_EXT:-}" \
  -V PORT_CH_RS422_XTX="${PORT_CH_RS422_XTX:-}" \
  -V PORT_CH_RS422_MIS_IF="${PORT_CH_RS422_MIS_IF:-}" \
  -V PORT_CH_RS422_SCOBC="${PORT_CH_RS422_SCOBC:-}" \
  -V PORT_CH_RS422_PCU_PIC2="${PORT_CH_RS422_PCU_PIC2:-}" \
  -V PORT_CH_RS422_PCU_PIC1="${PORT_CH_RS422_PCU_PIC1:-}" \
  -V PORT_CH_RS422_RESERVE="${PORT_CH_RS422_RESERVE:-}" \
  -V PORT_CH_LVTTL_AOBC="${PORT_CH_LVTTL_AOBC:-}" \
  -V PORT_CH_LVTTL_RESERVE="${PORT_CH_LVTTL_RESERVE:-}" \
  -V PORT_CH_LVTTL_STX="${PORT_CH_LVTTL_STX:-}" \
  -V PORT_CH_LVTTL_TOBC="${PORT_CH_LVTTL_TOBC:-}" \
  -V PORT_CH_LVTTL_LOBC="${PORT_CH_LVTTL_LOBC:-}" \
  "spaghetti.${KBLE_ENV:-sils}.jsonnet"
